version : '3.0'
services:
        jenkins:   
                image: jenkins/jenkins:latest
                ports:
                        - "18080:8080"
                volumes: 
                        - /root/jenkins/:/var/jenkins_home
